# Server configurations
server:
  host: "localhost"
  port: 8080

# Database credentials
database:
  user_name: "root"
  password: "Bhargavi@961819"
  port: 3306
  db_name: "first_go"
  host: "localhost"